### ISSUE TITLE
Offer of more queues!

### ISSUE THREAD

**Issue by mpadge** [coolbutuseless/priorityqueue#1]
Hey @coolbutuseless, in case you're interested in offering more queues, my [`dodgr` package](https://github.com/atfutures/dodgr) wraps a bunch of them in a [`src` sub-directory](https://github.com/ATFutures/dodgr/tree/main/src/heaps). Feel free to adapt, integrate, use to compare, whatever. They're mostly coded for strictly internal C/C++ usage, but easy enough to expose directly to R. They're also much faster than the `collections` ones, mostly because being internal they don't need the constant `PROTECT`/`UNPROTECT` calls and the likes. There's a [`compare_heaps()` function](https://atfutures.github.io/dodgr/reference/compare_heaps.html) to do benchmarking on a given network - especially intended to highlight that different queues/heaps perform differently for different tasks.

**Comment by coolbutuseless** [comment]
Thanks for the offer. I'm not adding anything else to priorityqueue at this stage, but will keep this in mind for when my needs change.
